### ISSUE TITLE
Access WP session variable in CI

### ISSUE THREAD

**Issue by tuonela** [dynamodan/wordpressigniter#7]
I am having trouble accessing the session variable I set in WordPress in Codeigniter. I am creating this functionality in my own plugin. Here is the code i am using:

`function get_property_filters($atts) {
	global $wp_session;
	foreach ($atts as $key => $value) {
		if ($key == 'prop_type') {
			$wp_session['property_type'] = $value;
		} else {
			$wp_session['property_type'] = 'land';
		}
	}
	return '<pre>'.print_r($wp_session).'</pre>';
}
add_shortcode('property_filters', 'get_property_filters');`

**Comment by dynamodan** [comment]
Does the $wp_session array contain anything?  One thing to keep in mind about the WordPressIgniter plugin, is how early in the wp core load the CI app is executed.  You may be setting a key in one place, but the code you read it from in another has already run.

**Comment by tuonela** [comment]
The $wp_session array does contain the session variable I am setting. I see what you are saying about how my plugin may be setting a variable but the CI code has run. However, this plugin creates shortcodes for the editor in the admin area, so I don't think CI would have loaded yet? Thank you for your quick response!

**Comment by dynamodan** [comment]
Are you expecting the WordPressIgniter plugin to run in the admin interface?  If so, that could be the problem.  See the statement that reads something like ```if(!is_admi()) { ...``` around line 34.

**Comment by tuonela** [comment]
I don't think I am. I really am just trying to retrieve an attribute from a shortcode insertion in a page and send that value to my CI page to use as a query filter.
