### ISSUE TITLE
Does this Plugin work with CI version 3.0

### ISSUE THREAD

**Issue by hakimny** [dynamodan/wordpressigniter#9]
Hi Dan,

I am getting this error when trying to view a test page that has the [wordpressigniter] shortcode
Warning: include(VIEWPATHerrors/html/error_php.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/wp-igniter/codeigniter/system/core/Exceptions.php on line 269

Warning: include(): Failed opening 'VIEWPATHerrors/html/error_php.php' for inclusion (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/wp-igniter/codeigniter/system/core/Exceptions.php on line 269

Warning: include(VIEWPATHerrors/html/error_php.php): failed to open stream: No such file or directory in /Applications/XAMPP/xamppfiles/htdocs/wp-igniter/codeigniter/system/core/Exceptions.php on line 269

Warning: include(): Failed opening 'VIEWPATHerrors/html/error_php.php' for inclusion (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in /Applications/XAMPP/xamppfiles/htdocs/wp-igniter/codeigniter/system/core/Exceptions.php on line 269

My App folder is wp-igniter
codeigniter folder is called codeigniter 
path : wp-igniter/codeigniter

Any help on this is highly appreciated

thx
Hakim

**Comment by hakimny** [comment]
I go it to work, after using a new installation, not sure if there was some residual code from all the tests I have done trying to make this work with different tricks.

Thx

**Comment by hakimny** [comment]
Hi Dan,

After testing multiple scenarios , I came up to the conclusion that codeigniter folder has to be outside of the folder containing wordpress,can you confirm this.

Thx
Hakim

**Comment by dynamodan** [comment]
Wow, I'm surprised that CodeIgniter 3.0 ran at all.  Regarding CodeIgniter needing to be outside WordPress, it's not only a good conclusion, but a fantastic strategy to keep CodeIgniter well outside of not only WordPress, but outside the docroot.  You should do this with as much code as possible.

**Comment by victorzhou10** [comment]
Sorry I have the same problem like hakimny and I get the same error even if I place codeigniter folder out of wordpress, and even out of htdosc.
my directory looks like the followng:
D:xampp/htdosc/wordpress
D:xampp/htdosc/codeigniter

I set the path like this: 
D:xampp/htdosc/codeigniter/

what can I do to deal with the problem?

**Comment by dynamodan** [comment]
Thanks guys for your responses.  I'm not sure what the fix was, and not really able to support any kind of windows issues.
